intel_adsp: ptl: Add missing definition [INTERNAL]
Fixes:
./zephyr/soc/xtensa/intel_adsp/common/ipc.c:96:23:
error: use of undeclared identifier 'INTEL_ADSP_IPC_ACE1X_TDA_DONE'

Signed-off-by: Flavio Ceolin <flavio.ceolin@intel.com>